import { useState, useEffect } from "react";
import { invokeLLM } from "@/lib/invokeLLM";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Sparkles,
  Loader2,
  Copy,
  CheckCircle2,
  Lightbulb,
  FileText,
  Target,
  AlertTriangle,
  BookOpen,
  ClipboardCopy
} from "lucide-react";

export default function AIProactiveDocumentationAssistant({ 
  analysisResults, 
  pdgmData, 
  navigationData,
  qualityScore 
}) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [suggestions, setSuggestions] = useState(null);
  const [error, setError] = useState(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState(null);

  // Auto-generate when data is available
  useEffect(() => {
    if (analysisResults && pdgmData && !suggestions && !isGenerating && !autoGenerated) {
      generateSuggestions();
      setAutoGenerated(true);
    }
  }, [analysisResults, pdgmData]);

  const generateSuggestions = async () => {
    if (!analysisResults || !pdgmData) return;

    setIsGenerating(true);
    setError(null);

    try {
      const result = await invokeLLM({
        prompt: `You are an expert OASIS clinical documentation specialist. Review this OASIS analysis and generate SPECIFIC, ACTIONABLE documentation improvement suggestions with exact example text.

ANALYSIS RESULTS:
${JSON.stringify({
  overall_score: analysisResults.overall_score,
  accuracy_score: analysisResults.accuracy_score,
  compliance_score: analysisResults.compliance_score,
  accuracy_issues: analysisResults.accuracy_issues?.slice(0, 8),
  compliance_concerns: analysisResults.compliance_concerns?.slice(0, 8),
  validation_issues: analysisResults.validation_summary?.issues?.slice(0, 5),
  revenue_tips: analysisResults.revenue_tips?.slice(0, 5)
}, null, 2)}

PDGM DATA:
${JSON.stringify(pdgmData, null, 2)}

NAVIGATION DATA:
${JSON.stringify(navigationData || {}, null, 2)}

QUALITY SCORES:
${JSON.stringify(qualityScore || {}, null, 2)}

TASK: Generate proactive documentation improvement suggestions focusing on:
1. Areas with low scores or high-severity issues
2. Compliance and accuracy problems
3. Revenue optimization opportunities
4. PDGM grouping discrepancies

For each suggestion, provide:
- Priority level (critical/high/medium)
- The specific OASIS item or documentation area
- Current documentation problem (what's wrong or missing)
- Why it matters (compliance, revenue, accuracy impact)
- EXACT before/after example text showing how to improve
- M-item scoring impact if applicable
- CMS guideline reference

Focus on TOP 10 most impactful suggestions. Be extremely specific with example text.

Return JSON:
{
  "priority_level": "critical/high/medium - overall documentation urgency",
  "total_issues_found": 0,
  "critical_count": 0,
  "high_count": 0,
  "summary": "1-2 sentence overview of documentation needs",
  "suggestions": [
    {
      "priority": "critical/high/medium",
      "category": "functional/diagnosis/compliance/timing/other",
      "oasis_item": "M-item code or area",
      "problem_identified": "specific problem description",
      "why_it_matters": "impact on compliance/revenue/accuracy",
      "revenue_impact": "$ estimate if applicable",
      "current_documentation_example": "what's currently documented or missing",
      "improved_documentation_example": "exact text to use instead",
      "before_after": {
        "before": "weak example text",
        "after": "strong example text with measurements and specifics"
      },
      "key_improvements": ["list of what makes the after better"],
      "m_item_scoring_impact": "how this affects M-item scores",
      "cms_reference": "relevant guideline",
      "quick_tip": "one sentence tip for this area"
    }
  ],
  "quick_wins": [
    {
      "item": "what to fix",
      "action": "simple action",
      "example_text": "exact text to add",
      "time_to_fix": "time estimate"
    }
  ],
  "documentation_templates": [
    {
      "use_case": "when to use this template",
      "template_text": "fill-in-the-blank template",
      "example_filled": "completed example"
    }
  ],
  "overall_recommendation": "main action user should take"
}`,
        response_json_schema: {
          type: "object",
          properties: {
            priority_level: { type: "string" },
            total_issues_found: { type: "number" },
            critical_count: { type: "number" },
            high_count: { type: "number" },
            summary: { type: "string" },
            suggestions: { type: "array", items: { type: "object" } },
            quick_wins: { type: "array", items: { type: "object" } },
            documentation_templates: { type: "array", items: { type: "object" } },
            overall_recommendation: { type: "string" }
          }
        }
      });

      setSuggestions(result);
    } catch (err) {
      console.error("Documentation suggestions error:", err);
      setError("Failed to generate documentation suggestions. Please try again.");
    }

    setIsGenerating(false);
  };

  const handleCopy = (text, index) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const getPriorityBadge = (priority) => {
    const styles = {
      critical: 'bg-red-600 text-white',
      high: 'bg-orange-500 text-white',
      medium: 'bg-yellow-500 text-white'
    };
    return styles[priority] || styles.medium;
  };

  const getCategoryIcon = (category) => {
    const icons = {
      functional: Target,
      diagnosis: FileText,
      compliance: BookOpen,
      timing: AlertTriangle,
      other: Lightbulb
    };
    return icons[category] || Lightbulb;
  };

  const getPriorityColor = (priority) => {
    const colors = {
      critical: { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-700' },
      high: { bg: 'bg-orange-50', border: 'border-orange-200', text: 'text-orange-700' },
      medium: { bg: 'bg-yellow-50', border: 'border-yellow-200', text: 'text-yellow-700' }
    };
    return colors[priority] || colors.medium;
  };

  if (!analysisResults || !pdgmData) {
    return null;
  }

  return (
    <Card className="border-2 border-navy-200">
      <CardHeader className="pb-3 bg-gradient-to-r from-navy-50 to-pink-50">
        <CardTitle className="text-lg flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-navy-600" />
            AI Documentation Assistant
          </div>
          {suggestions && (
            <div className="flex items-center gap-2">
              <Badge className={getPriorityBadge(suggestions.priority_level)}>
                {suggestions.priority_level} priority
              </Badge>
              <Badge variant="outline">
                {suggestions.total_issues_found} issues
              </Badge>
            </div>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4 pt-4">
        {isGenerating ? (
          <div className="text-center py-8">
            <Loader2 className="w-8 h-8 animate-spin text-navy-600 mx-auto mb-3" />
            <p className="text-sm text-slate-600">AI is analyzing your documentation and generating improvement suggestions...</p>
            <p className="text-xs text-slate-400 mt-1">Creating specific examples and templates</p>
          </div>
        ) : !suggestions ? (
          <Button
            onClick={generateSuggestions}
            className="w-full bg-navy-600 hover:bg-navy-700"
          >
            <Sparkles className="w-4 h-4 mr-2" /> Generate Documentation Suggestions
          </Button>
        ) : (
          <>
            {/* Summary Alert */}
            <Alert className={`${getPriorityColor(suggestions.priority_level).bg} border-2 ${getPriorityColor(suggestions.priority_level).border}`}>
              <Sparkles className="w-4 h-4 text-navy-600" />
              <AlertDescription className={suggestions.priority_level.text}>
                <p className="font-semibold mb-1">{suggestions.summary}</p>
                <p className="text-sm">{suggestions.overall_recommendation}</p>
              </AlertDescription>
            </Alert>

            {/* Issue Count Summary */}
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-red-50 p-3 rounded-lg border border-red-200 text-center">
                <p className="text-xs text-red-600">Critical</p>
                <p className="text-2xl font-bold text-red-700">{suggestions.critical_count || 0}</p>
              </div>
              <div className="bg-orange-50 p-3 rounded-lg border border-orange-200 text-center">
                <p className="text-xs text-orange-600">High Priority</p>
                <p className="text-2xl font-bold text-orange-700">{suggestions.high_count || 0}</p>
              </div>
              <div className="bg-blue-50 p-3 rounded-lg border border-blue-200 text-center">
                <p className="text-xs text-blue-600">Total Issues</p>
                <p className="text-2xl font-bold text-blue-700">{suggestions.total_issues_found || 0}</p>
              </div>
            </div>

            {/* Quick Wins */}
            {suggestions.quick_wins?.length > 0 && (
              <div className="bg-green-50 p-4 rounded-lg border border-green-200">
                <h3 className="font-semibold text-green-900 mb-3 flex items-center gap-2">
                  <Target className="w-4 h-4" />
                  Quick Wins - Fast Improvements
                </h3>
                <div className="space-y-2">
                  {suggestions.quick_wins.map((win, idx) => (
                    <div key={idx} className="bg-white p-3 rounded border flex items-start justify-between gap-3">
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-800 mb-1">{win.item}</p>
                        <p className="text-xs text-slate-600 mb-2">{win.action}</p>
                        <div className="bg-blue-50 p-2 rounded border border-blue-200">
                          <p className="text-xs text-blue-600 font-medium mb-0.5">📝 Add this:</p>
                          <p className="text-sm text-blue-900 italic">"{win.example_text}"</p>
                        </div>
                      </div>
                      <div className="flex flex-col items-end gap-2">
                        <Badge variant="outline" className="text-xs">{win.time_to_fix}</Badge>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleCopy(win.example_text, `quick-${idx}`)}
                          className="h-7 px-2"
                        >
                          {copiedIndex === `quick-${idx}` ? (
                            <CheckCircle2 className="w-3 h-3 text-green-600" />
                          ) : (
                            <Copy className="w-3 h-3" />
                          )}
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Detailed Suggestions */}
            {suggestions.suggestions?.length > 0 && (
              <Accordion type="multiple" className="space-y-2">
                {suggestions.suggestions.map((suggestion, idx) => {
                  const colors = getPriorityColor(suggestion.priority);
                  const CategoryIcon = getCategoryIcon(suggestion.category);

                  return (
                    <AccordionItem key={idx} value={`suggestion-${idx}`} className="border rounded-lg">
                      <AccordionTrigger className={`px-4 py-3 hover:no-underline ${colors.bg} rounded-t-lg`}>
                        <div className="flex items-center justify-between w-full pr-4">
                          <div className="flex items-center gap-2">
                            <CategoryIcon className="w-4 h-4 text-navy-600" />
                            <span className="font-medium text-slate-800">{suggestion.oasis_item}</span>
                            <Badge className={getPriorityBadge(suggestion.priority)}>
                              {suggestion.priority}
                            </Badge>
                          </div>
                          {suggestion.revenue_impact && (
                            <Badge className="bg-green-600 text-white">
                              {suggestion.revenue_impact}
                            </Badge>
                          )}
                        </div>
                      </AccordionTrigger>
                      <AccordionContent className="px-4 pb-4 pt-2">
                        <div className="space-y-3">
                          {/* Problem & Impact */}
                          <div className="bg-red-50 p-3 rounded border border-red-200">
                            <p className="text-xs font-semibold text-red-700 mb-1">Problem Identified</p>
                            <p className="text-sm text-slate-800">{suggestion.problem_identified}</p>
                            <p className="text-xs text-orange-700 mt-2 bg-orange-50 p-1.5 rounded">
                              <strong>Impact:</strong> {suggestion.why_it_matters}
                            </p>
                          </div>

                          {/* Before/After Examples */}
                          {suggestion.before_after && (
                            <div className="space-y-2">
                              <p className="text-xs font-semibold text-slate-700">Documentation Examples</p>
                              
                              {/* Before */}
                              <div className="bg-red-50 p-3 rounded border border-red-200">
                                <div className="flex items-center justify-between mb-1">
                                  <p className="text-xs font-semibold text-red-700">❌ Weak Documentation</p>
                                </div>
                                <p className="text-sm text-slate-700 italic">"{suggestion.before_after.before}"</p>
                              </div>

                              {/* After */}
                              <div className="bg-green-50 p-3 rounded border-2 border-green-300">
                                <div className="flex items-center justify-between mb-1">
                                  <p className="text-xs font-semibold text-green-700">✅ Strong Documentation</p>
                                  <Button
                                    size="sm"
                                    variant="ghost"
                                    onClick={() => handleCopy(suggestion.before_after.after, `after-${idx}`)}
                                    className="h-6 px-2"
                                  >
                                    {copiedIndex === `after-${idx}` ? (
                                      <><CheckCircle2 className="w-3 h-3 mr-1 text-green-600" /> Copied</>
                                    ) : (
                                      <><Copy className="w-3 h-3 mr-1" /> Copy</>
                                    )}
                                  </Button>
                                </div>
                                <p className="text-sm text-slate-800 italic font-medium">"{suggestion.before_after.after}"</p>
                              </div>

                              {/* Key Improvements */}
                              {suggestion.key_improvements?.length > 0 && (
                                <div className="bg-blue-50 p-2 rounded border border-blue-200">
                                  <p className="text-xs font-semibold text-blue-700 mb-1">Why this is better:</p>
                                  <ul className="text-xs text-blue-800 space-y-0.5">
                                    {suggestion.key_improvements.map((imp, i) => (
                                      <li key={i}>✓ {imp}</li>
                                    ))}
                                  </ul>
                                </div>
                              )}
                            </div>
                          )}

                          {/* Improved Documentation Example (if before_after not provided) */}
                          {!suggestion.before_after && suggestion.improved_documentation_example && (
                            <div className="bg-green-50 p-3 rounded border-2 border-green-300">
                              <div className="flex items-center justify-between mb-1">
                                <p className="text-xs font-semibold text-green-700">Recommended Documentation</p>
                                <Button
                                  size="sm"
                                  variant="ghost"
                                  onClick={() => handleCopy(suggestion.improved_documentation_example, `improved-${idx}`)}
                                  className="h-6 px-2"
                                >
                                  {copiedIndex === `improved-${idx}` ? (
                                    <><CheckCircle2 className="w-3 h-3 mr-1 text-green-600" /> Copied</>
                                  ) : (
                                    <><Copy className="w-3 h-3 mr-1" /> Copy</>
                                  )}
                                </Button>
                              </div>
                              <p className="text-sm text-slate-800 italic">"{suggestion.improved_documentation_example}"</p>
                            </div>
                          )}

                          {/* M-Item Impact */}
                          {suggestion.m_item_scoring_impact && (
                            <div className="bg-navy-50 p-2 rounded border border-navy-200 text-xs">
                              <p className="font-medium text-navy-700">Scoring Impact: {suggestion.m_item_scoring_impact}</p>
                            </div>
                          )}

                          {/* CMS Reference */}
                          {suggestion.cms_reference && (
                            <div className="bg-slate-50 p-2 rounded border text-xs text-slate-600">
                              <strong>CMS Guideline:</strong> {suggestion.cms_reference}
                            </div>
                          )}

                          {/* Quick Tip */}
                          {suggestion.quick_tip && (
                            <div className="bg-indigo-50 p-2 rounded border border-indigo-200">
                              <p className="text-xs text-indigo-700 flex items-center gap-1">
                                <Lightbulb className="w-3 h-3" />
                                <strong>Quick Tip:</strong> {suggestion.quick_tip}
                              </p>
                            </div>
                          )}
                        </div>
                      </AccordionContent>
                    </AccordionItem>
                  );
                })}
              </Accordion>
            )}

            {/* Documentation Templates */}
            {suggestions.documentation_templates?.length > 0 && (
              <div className="bg-indigo-50 p-4 rounded-lg border border-indigo-200">
                <h3 className="font-semibold text-indigo-900 mb-3 flex items-center gap-2">
                  <ClipboardCopy className="w-4 h-4" />
                  Documentation Templates
                </h3>
                <div className="space-y-3">
                  {suggestions.documentation_templates.map((template, idx) => (
                    <div key={idx} className="bg-white p-3 rounded border">
                      <p className="text-xs font-semibold text-slate-700 mb-1">{template.use_case}</p>
                      <div className="bg-slate-50 p-2 rounded border mb-2">
                        <p className="text-xs text-slate-500 mb-1">Template:</p>
                        <p className="text-sm text-slate-800 font-mono">{template.template_text}</p>
                      </div>
                      <div className="bg-blue-50 p-2 rounded border border-blue-200">
                        <div className="flex items-center justify-between mb-1">
                          <p className="text-xs text-blue-600 font-medium">Example (filled):</p>
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => handleCopy(template.example_filled, `template-${idx}`)}
                            className="h-6 px-2"
                          >
                            {copiedIndex === `template-${idx}` ? (
                              <CheckCircle2 className="w-3 h-3 text-green-600" />
                            ) : (
                              <Copy className="w-3 h-3" />
                            )}
                          </Button>
                        </div>
                        <p className="text-sm text-blue-900 italic">"{template.example_filled}"</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Re-generate Button */}
            <Button
              onClick={() => { setSuggestions(null); setAutoGenerated(false); }}
              variant="outline"
              size="sm"
              className="w-full"
            >
              Generate New Suggestions
            </Button>
          </>
        )}

        {error && (
          <Alert className="bg-red-50 border-red-200">
            <AlertDescription className="text-red-800 text-sm">{error}</AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}