export const OASIS_SECTIONS = [
  {
    id: "demographics",
    title: "Clinical Record & Status",
    icon: "👤",
    questions: [
      {
        id: "m0069",
        label: "M0069 — Prognosis",
        description: "Does this patient have a condition that has a life expectancy of a year or less?",
        type: "radio",
        options: [{ value: 0, label: "0 — No" }, { value: 1, label: "1 — Yes" }],
      },
      {
        id: "m1020",
        label: "M1020 — Primary Diagnosis",
        description: "Primary diagnosis that prompted home care admission.",
        type: "select",
        options: [
          { value: 0, label: "Select primary diagnosis..." },
          { value: 1, label: "Diabetes Mellitus" },
          { value: 2, label: "Heart Failure / CHF" },
          { value: 3, label: "COPD / Asthma" },
          { value: 4, label: "Hypertension" },
          { value: 5, label: "Wound / Pressure Ulcer" },
          { value: 6, label: "Orthopedic (Hip/Knee)" },
          { value: 7, label: "Stroke / CVA" },
          { value: 8, label: "Other" },
        ],
      },
      {
        id: "m1030",
        label: "M1030 — Therapies at Home",
        description: "Intravenous/infusion therapy, parenteral nutrition, or enteral nutrition received at home.",
        type: "radio",
        options: [
          { value: 0, label: "0 — None" },
          { value: 1, label: "1 — IV/Infusion therapy" },
          { value: 2, label: "2 — Parenteral/Enteral nutrition" },
        ],
      },
    ],
  },
  {
    id: "living",
    title: "Living Arrangements & Supports",
    icon: "🏠",
    questions: [
      {
        id: "m1100",
        label: "M1100 — Patient Living Situation",
        description: "Which of the following best describes the patient's residential circumstance and availability of assistance?",
        type: "radio",
        options: [
          { value: 0, label: "01 — Patient lives alone with no assistance available" },
          { value: 1, label: "02 — Patient lives alone with scheduled assistance" },
          { value: 2, label: "03 — Patient lives with others with no assistance from them" },
          { value: 3, label: "04 — Patient lives with others who provide assistance" },
        ],
      },
    ],
  },
  {
    id: "sensory",
    title: "Sensory Status",
    icon: "👁",
    questions: [
      {
        id: "m1730",
        label: "M1730 — Depression Screening",
        description: "PHQ-2 positive screen — 'Little interest or pleasure in doing things' or 'Feeling down, depressed, or hopeless' in last 2 weeks?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No (negative screen)" },
          { value: 1, label: "1 — Yes to one question (positive screen)" },
          { value: 2, label: "2 — Yes to both questions (positive screen)" },
        ],
        alert: { threshold: 1, message: "Positive depression screen — psychosocial assessment indicated." }
      },
      {
        id: "m1740",
        label: "M1740 — Cognitive, Behavioral & Psychiatric Symptoms",
        description: "Behavioral symptoms that could be due to a cognitive, mental, or behavioral impairment.",
        type: "radio",
        options: [
          { value: 0, label: "0 — None of the behaviors" },
          { value: 1, label: "1 — Memory deficit / recall difficulty" },
          { value: 2, label: "2 — Impaired decision-making" },
          { value: 3, label: "3 — Verbal disruption / disruptive behavior" },
          { value: 4, label: "4 — Physical aggression" },
        ],
      },
      {
        id: "m1700",
        label: "M1700 — Cognitive Functioning",
        description: "Patient's current (day of assessment) level of alertness, orientation, comprehension, concentration, and immediate memory.",
        type: "radio",
        options: [
          { value: 0, label: "0 — Alert/oriented, able to focus and shift attention" },
          { value: 1, label: "1 — Requires prompting (cues) to focus" },
          { value: 2, label: "2 — Requires assistance and clinical supervision" },
          { value: 3, label: "3 — Requires considerable assistance — very short attention span" },
          { value: 4, label: "4 — Totally dependent due to disturbances" },
        ],
      },
    ],
  },
  {
    id: "respiratory",
    title: "Respiratory Status",
    icon: "🫁",
    questions: [
      {
        id: "m1400",
        label: "M1400 — Respiratory Status: Dyspnea",
        description: "Shortness of breath or labored breathing observed at assessment.",
        type: "radio",
        alert: { threshold: 2, message: "Significant dyspnea — respiratory management interventions strongly recommended." },
        options: [
          { value: 0, label: "0 — Not short of breath" },
          { value: 1, label: "1 — Short of breath when walking over 20 feet" },
          { value: 2, label: "2 — Short of breath with moderate exertion" },
          { value: 3, label: "3 — Short of breath with minimal exertion at rest" },
          { value: 4, label: "4 — Short of breath with minimal exertion or at rest" },
        ],
      },
    ],
  },
  {
    id: "cardiac",
    title: "Cardiac & Elimination",
    icon: "❤️",
    questions: [
      {
        id: "m1340",
        label: "M1340 — Surgical Wound",
        description: "Does the patient have a surgical wound?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No" },
          { value: 1, label: "1 — Yes — not infected" },
          { value: 2, label: "2 — Yes — infected/complications" },
        ],
        alert: { threshold: 1, message: "Surgical wound present — wound care protocol required." }
      },
      {
        id: "m1306",
        label: "M1306 — Unhealed Pressure Ulcer(s)",
        description: "Does the patient have at least one unhealed pressure ulcer/injury at any stage?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No" },
          { value: 1, label: "1 — Yes" },
        ],
        alert: { threshold: 1, message: "Pressure ulcer present — wound care interventions required for compliance." }
      },
      {
        id: "m1350",
        label: "M1350 — Skin Lesion or Open Wound",
        description: "Does the patient have a skin lesion or open wound, excluding pressure ulcers and surgical wounds?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No" },
          { value: 1, label: "1 — Yes" },
        ],
      },
    ],
  },
  {
    id: "functional",
    title: "Functional Status & ADLs",
    icon: "🧍",
    questions: [
      {
        id: "m1800",
        label: "M1800 — Grooming",
        description: "Current ability to tend to personal hygiene needs (i.e., washing face and hands, hair care, shaving).",
        type: "radio",
        options: [
          { value: 0, label: "0 — Able to groom self unaided" },
          { value: 1, label: "1 — Grooming utensils must be placed within reach" },
          { value: 2, label: "2 — Someone must assist the patient" },
          { value: 3, label: "3 — Patient depends entirely upon someone else" },
        ],
      },
      {
        id: "m1860",
        label: "M1860 — Ambulation/Locomotion",
        description: "Current ability to walk safely, once in a standing position.",
        type: "radio",
        alert: { threshold: 2, message: "Impaired ambulation detected — fall prevention interventions strongly recommended." },
        options: [
          { value: 0, label: "0 — Able to ambulate on even/uneven surfaces" },
          { value: 1, label: "1 — With minor difficulty on uneven surfaces" },
          { value: 2, label: "2 — Requires use of a one-handed device" },
          { value: 3, label: "3 — Requires use of a two-handed device" },
          { value: 4, label: "4 — Requires use of a wheelchair" },
          { value: 5, label: "5 — Unable to ambulate" },
        ],
      },
      {
        id: "m1810",
        label: "M1810 — Upper Body Dressing",
        description: "Current ability to dress upper body safely (excluding prostheses).",
        type: "radio",
        options: [
          { value: 0, label: "0 — No assistance needed" },
          { value: 1, label: "1 — With minor difficulty or helper makes adaptations" },
          { value: 2, label: "2 — Someone must assist" },
          { value: 3, label: "3 — Totally dependent" },
        ],
      },
      {
        id: "m1820",
        label: "M1820 — Lower Body Dressing",
        description: "Current ability to dress lower body safely (excluding prostheses).",
        type: "radio",
        options: [
          { value: 0, label: "0 — No assistance needed" },
          { value: 1, label: "1 — With minor difficulty or helper makes adaptations" },
          { value: 2, label: "2 — Someone must assist" },
          { value: 3, label: "3 — Totally dependent" },
        ],
      },
    ],
  },
  {
    id: "medications",
    title: "Medications",
    icon: "💊",
    questions: [
      {
        id: "m2001",
        label: "M2001 — Drug Regimen Review",
        description: "Was a complete drug regimen review conducted? Did any identified drug issues require follow-up?",
        type: "radio",
        alert: { threshold: 1, message: "Drug regimen issues identified — medication management education is required." },
        options: [
          { value: 0, label: "0 — No issues found during review" },
          { value: 1, label: "1 — Issues found, physician contacted within 24 hours" },
          { value: 2, label: "2 — Issues found, physician not contacted" },
        ],
      },
      {
        id: "m2010",
        label: "M2010 — High-Risk Drug Education",
        description: "Has the patient/caregiver received education on high-risk drug?",
        type: "radio",
        options: [
          { value: 0, label: "0 — Not applicable — no high-risk drugs" },
          { value: 1, label: "1 — Education completed" },
          { value: 2, label: "2 — Education not completed" },
        ],
      },
      {
        id: "m2020",
        label: "M2020 — Management of Oral Medications",
        description: "Patient's current ability to prepare and take all oral medications reliably and safely.",
        type: "radio",
        options: [
          { value: 0, label: "0 — Able to independently take correct medications" },
          { value: 1, label: "1 — Able if given daily reminders" },
          { value: 2, label: "2 — Able to take only if medication is prepared" },
          { value: 3, label: "3 — Unable to take medication" },
        ],
      },
    ],
  },
  {
    id: "fallrisk",
    title: "Fall Risk",
    icon: "⚠️",
    questions: [
      {
        id: "m1910",
        label: "M1910 — Fall Risk Assessment",
        description: "Has the patient had two or more falls in the past year or any fall with injury?",
        type: "radio",
        alert: { threshold: 1, message: "Fall history identified — comprehensive fall prevention protocol is required." },
        options: [
          { value: 0, label: "0 — No falls in past year" },
          { value: 1, label: "1 — One fall or any fall with injury" },
          { value: 2, label: "2 — Two or more falls" },
        ],
      },
      {
        id: "m1900",
        label: "M1900 — Prior Functioning",
        description: "In the 2 weeks prior to the current illness, exacerbation, or injury, patient's ADL ability was:",
        type: "radio",
        options: [
          { value: 0, label: "0 — Independent — no assistance needed" },
          { value: 1, label: "1 — Required some assistance" },
          { value: 2, label: "2 — Required considerable assistance" },
          { value: 3, label: "3 — Mostly or totally dependent" },
          { value: 4, label: "4 — Unknown" },
        ],
      },
    ],
  },
  {
    id: "bathing",
    title: "Bathing & Toileting",
    icon: "🚿",
    questions: [
      {
        id: "m1830",
        label: "M1830 — Bathing",
        description: "Current ability to wash entire body safely. Excludes grooming (washing face, shampooing hair).",
        type: "radio",
        options: [
          { value: 0, label: "0 — Able to bathe self in shower/tub independently" },
          { value: 1, label: "1 — With minimal person assistance to bathe" },
          { value: 2, label: "2 — With partial person assistance; patient performs part" },
          { value: 3, label: "3 — With extensive person assistance; minimal patient effort" },
          { value: 4, label: "4 — Unable to bathe self; total person assistance" },
          { value: 5, label: "5 — Unable to bathe self and refused" },
          { value: 6, label: "6 — Unable to rate — patient has artificial opening" },
        ],
      },
      {
        id: "m1840",
        label: "M1840 — Toilet Transferring",
        description: "Current ability to get to and from the toilet or bedside commode safely.",
        type: "radio",
        options: [
          { value: 0, label: "0 — Able to independently transfer" },
          { value: 1, label: "1 — Able to transfer with minimal assistance" },
          { value: 2, label: "2 — Able to bear weight and pivot with assistance" },
          { value: 3, label: "3 — Unable to bear weight; totally dependent" },
          { value: 4, label: "4 — Bedfast, unable to use toilet/commode" },
        ],
      },
      {
        id: "m1845",
        label: "M1845 — Toileting Hygiene",
        description: "Current ability to maintain perineal hygiene, adjust clothing before and after using toilet/commode/bedpan.",
        type: "radio",
        options: [
          { value: 0, label: "0 — Able to manage all toileting independently" },
          { value: 1, label: "1 — Can manage with use of devices/difficulty" },
          { value: 2, label: "2 — Someone must help with clothing or use devices" },
          { value: 3, label: "3 — Patient depends entirely on another person" },
        ],
      },
    ],
  },
  {
    id: "transferring",
    title: "Transferring & Bed Mobility",
    icon: "🛏️",
    questions: [
      {
        id: "m1850",
        label: "M1850 — Transferring",
        description: "Current ability to move safely from bed to chair, or standing position if walking.",
        type: "radio",
        alert: { threshold: 2, message: "Significant transfer difficulty — fall prevention and caregiver training required." },
        options: [
          { value: 0, label: "0 — Able to independently transfer" },
          { value: 1, label: "1 — Transfers with minimal human assistance" },
          { value: 2, label: "2 — Unable to transfer self but able to bear weight and pivot" },
          { value: 3, label: "3 — Unable to transfer and unable to bear weight" },
          { value: 4, label: "4 — Bedfast, unable to transfer" },
        ],
      },
      {
        id: "m1860",
        label: "M1860 — Ambulation/Locomotion",
        description: "Current ability to walk safely, once in a standing position, or use of wheelchair.",
        type: "radio",
        options: [
          { value: 0, label: "0 — Able to independently walk on all surfaces" },
          { value: 1, label: "1 — With minor difficulty on uneven surfaces" },
          { value: 2, label: "2 — Requires use of one-handed device" },
          { value: 3, label: "3 — Requires use of two-handed device or walker" },
          { value: 4, label: "4 — Able to wheel self independently in wheelchair" },
          { value: 5, label: "5 — Unable to ambulate; bedfast" },
        ],
      },
    ],
  },
  {
    id: "eating",
    title: "Eating & Nutrition",
    icon: "🍽️",
    questions: [
      {
        id: "m1870",
        label: "M1870 — Feeding or Eating",
        description: "Current ability to feed self meals and snacks safely.",
        type: "radio",
        options: [
          { value: 0, label: "0 — Able to independently feed self" },
          { value: 1, label: "1 — Able to feed self with devices or setup help" },
          { value: 2, label: "2 — Unable to feed self and needs person assistance" },
          { value: 3, label: "3 — Totally dependent on another person" },
        ],
      },
      {
        id: "m1033",
        label: "M1033 — Risk for Hospitalization",
        description: "Which best describes the overall risk for hospitalization for this patient?",
        type: "radio",
        alert: { threshold: 1, message: "High hospitalization risk — proactive monitoring and care coordination required." },
        options: [
          { value: 0, label: "0 — Low risk" },
          { value: 1, label: "1 — Medium risk" },
          { value: 2, label: "2 — High risk" },
        ],
      },
    ],
  },
  {
    id: "pain",
    title: "Pain & Symptom Management",
    icon: "😣",
    questions: [
      {
        id: "m1242",
        label: "M1242 — Frequency of Pain",
        description: "What is the frequency of patient-reported pain?",
        type: "radio",
        alert: { threshold: 2, message: "Frequent pain — pain management interventions required." },
        options: [
          { value: 0, label: "0 — No pain" },
          { value: 1, label: "1 — Pain less often than daily" },
          { value: 2, label: "2 — Daily but not constantly" },
          { value: 3, label: "3 — Constant pain" },
        ],
      },
      {
        id: "m1300",
        label: "M1300 — Pressure Ulcer Risk",
        description: "Does this patient have a Risk Assessment for Pressure Ulcers (e.g., Braden)?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No risk factors" },
          { value: 1, label: "1 — At risk for pressure ulcers" },
        ],
      },
    ],
  },
  {
    id: "urinary",
    title: "Urinary & Bowel Status",
    icon: "🚽",
    questions: [
      {
        id: "m1610",
        label: "M1610 — Urinary Incontinence",
        description: "How often does the patient have urinary incontinence (loss of bladder control)?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No incontinence or catheter" },
          { value: 1, label: "1 — Occasional stress incontinence" },
          { value: 2, label: "2 — During day/night; daily pads required" },
          { value: 3, label: "3 — All the time; no control" },
          { value: 4, label: "NA — Patient has indwelling/suprapubic catheter" },
        ],
      },
      {
        id: "m1620",
        label: "M1620 — Bowel Incontinence",
        description: "How often does the patient have bowel incontinence (loss of bowel control)?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No bowel incontinence or ostomy" },
          { value: 1, label: "1 — Less than once weekly" },
          { value: 2, label: "2 — One to three times per week" },
          { value: 3, label: "3 — Four to six times per week" },
          { value: 4, label: "4 — Daily or more often" },
          { value: 5, label: "5 — Patient has ostomy for bowel elimination" },
        ],
      },
      {
        id: "m1630",
        label: "M1630 — Ostomy",
        description: "Does the patient have a surgically created ostomy for elimination?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No ostomy for elimination" },
          { value: 1, label: "1 — Patient has ostomy and managing independently" },
          { value: 2, label: "2 — Patient has ostomy and requires assistance" },
        ],
      },
    ],
  },
  {
    id: "therapy",
    title: "Therapy Needs",
    icon: "🏃",
    questions: [
      {
        id: "m2102",
        label: "M2102 — Physical Therapy",
        description: "Does the comprehensive assessment indicate a need for physical therapy?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No need for PT" },
          { value: 1, label: "1 — PT needed" },
        ],
      },
      {
        id: "m2110",
        label: "M2110 — Occupational Therapy",
        description: "Does the comprehensive assessment indicate a need for occupational therapy?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No need for OT" },
          { value: 1, label: "1 — OT needed" },
        ],
      },
      {
        id: "m2200",
        label: "M2200 — Speech-Language Pathology",
        description: "Does the comprehensive assessment indicate a need for speech-language pathology?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No need for SLP" },
          { value: 1, label: "1 — SLP needed" },
        ],
      },
    ],
  },
  {
    id: "discharge",
    title: "Discharge & Goals",
    icon: "🎯",
    questions: [
      {
        id: "m2401",
        label: "M2401 — Intervention Synopsis",
        description: "Were intervention(s) implemented to address medication issues?",
        type: "radio",
        options: [
          { value: 0, label: "0 — No" },
          { value: 1, label: "1 — Yes" },
          { value: 9, label: "NA — No medication issues identified" },
        ],
      },
      {
        id: "m2420",
        label: "M2420 — Discharge Disposition",
        description: "Where is the patient after discharge from agency?",
        type: "radio",
        options: [
          { value: 1, label: "1 — Remained in community (not in facility)" },
          { value: 2, label: "2 — Transferred to hospital" },
          { value: 3, label: "3 — Transferred to rehab facility" },
          { value: 4, label: "4 — Transferred to nursing home" },
          { value: 5, label: "5 — Other" },
          { value: 9, label: "UK — Unknown" },
        ],
      },
    ],
  },
];