// crop-logo.mjs — prepare the cover logo asset for the manuals.
//
// Precisely crops the PennSync app-icon logo: detects the colored icon (ignoring
// the white margin AND the soft gray drop-shadow), crops to a centered square,
// and clips to a rounded rect with transparent corners so it sits flush on the
// navy cover — no white space, nothing cut off. Deterministic (no screenshot
// guesswork). Writes the 512x512 RGBA PNG and regenerates logo.data.mjs.
//
//   node scripts/manuals/crop-logo.mjs
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SRC = resolve(ROOT, 'public/manuals/assets/pennsync-logo.png');
const OUT = resolve(ROOT, 'public/manuals/assets/pennsync-logo-cropped.png');
const DATA = resolve(ROOT, 'scripts/manuals/logo.data.mjs');
const SIZE = 512;

const img = await loadImage(SRC);
const W = img.width, H = img.height;
const c = createCanvas(W, H);
const x = c.getContext('2d');
x.drawImage(img, 0, 0);
const d = x.getImageData(0, 0, W, H).data;

// "icon" pixel = clearly colored (saturated) OR dark — excludes white margin and
// the light-gray drop-shadow (both low saturation + bright).
let minX = W, minY = H, maxX = 0, maxY = 0;
for (let y = 0; y < H; y++) {
  for (let xx = 0; xx < W; xx++) {
    const o = (y * W + xx) * 4;
    const r = d[o], g = d[o + 1], b = d[o + 2];
    const mx = Math.max(r, g, b), mn = Math.min(r, g, b);
    const isIcon = (mx - mn) > 34 || mx < 205;
    if (isIcon) {
      if (xx < minX) minX = xx; if (xx > maxX) maxX = xx;
      if (y < minY) minY = y; if (y > maxY) maxY = y;
    }
  }
}
const bw = maxX - minX + 1, bh = maxY - minY + 1;
console.log(`icon bounds: x[${minX}..${maxX}] y[${minY}..${maxY}]  ${bw}x${bh}`);

// Centered square cropped to the icon bounds, biting ~3px INSIDE each edge so no
// anti-aliased white margin survives on the straight edges.
const inset = Math.round(Math.max(bw, bh) * 0.006);
let side = Math.max(bw, bh) - inset * 2;
const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2;
let sx = Math.round(cx - side / 2), sy = Math.round(cy - side / 2);
if (sx < 0) sx = 0; if (sy < 0) sy = 0;
if (sx + side > W) side = W - sx; if (sy + side > H) side = H - sy;
console.log(`crop square: x=${sx} y=${sy} side=${side} (inset ${inset})`);

// Output with rounded-rect clip (transparent corners).
const out = createCanvas(SIZE, SIZE);
const o = out.getContext('2d');
const rad = Math.round(SIZE * 0.222);
o.clearRect(0, 0, SIZE, SIZE);
o.beginPath();
o.moveTo(rad, 0);
o.arcTo(SIZE, 0, SIZE, SIZE, rad);
o.arcTo(SIZE, SIZE, 0, SIZE, rad);
o.arcTo(0, SIZE, 0, 0, rad);
o.arcTo(0, 0, SIZE, 0, rad);
o.closePath();
o.clip();
o.imageSmoothingEnabled = true;
o.imageSmoothingQuality = 'high';
o.drawImage(c, sx, sy, side, side, 0, 0, SIZE, SIZE);
const png = out.toBuffer('image/png');
writeFileSync(OUT, png);
console.log(`wrote ${OUT}`);

// Regenerate the inlined data-URI module used by the manual cover.
const dataMod =
  '// Auto-generated by scripts/manuals/crop-logo.mjs: PennSync app-icon logo cropped\n' +
  '// precisely to the icon edge (white margin + drop-shadow removed) with transparent\n' +
  '// rounded corners, so it sits flush on the navy cover — no white space, nothing cut off.\n' +
  'export const LOGO_DATA_URI = "data:image/png;base64,' + png.toString('base64') + '";\n';
writeFileSync(DATA, dataMod);
console.log(`wrote ${DATA}`);
