import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import { useAICall } from "@/hooks/useAICall";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Sparkles, Copy, CheckCircle2, Edit3, Save, Eye } from "lucide-react";
import AIFieldIndicator from "@/components/ui/ai-field-indicator";
import ProgressFeedback from "@/components/ui/progress-feedback";
import RealTimeDocumentationReviewer from "../documentation/RealTimeDocumentationReviewer";
import { buildAdmissionNotePrompt, ADMISSION_NOTE_SCHEMA } from "./admissionNotePrompt.js";
import { toast } from 'sonner';

export default function AIAdmissionNoteGenerator({ referralData, onNoteGenerated, autoGenerate = false }) {
  const ai = useAICall();
  const [generatedNote, setGeneratedNote] = useState("");
  const [isEditing, setIsEditing] = useState(false);
  const [editedNote, setEditedNote] = useState("");
  const [generationStage, setGenerationStage] = useState(0);
  const [showReviewer, setShowReviewer] = useState(false);
  const progressIntervalRef = useRef(null);
  // Monotonic id so a slower, older generation (e.g. an earlier Regenerate click)
  // can't overwrite the result of a newer one.
  const generateReqIdRef = useRef(0);
  // Track the referralData we've already auto-generated for so a persistent
  // generation failure can't re-fire the (billed) LLM call in a loop; explicit
  // Regenerate still works.
  const autoGeneratedForRef = useRef(null);

  // Clear the progress interval if the component unmounts mid-generation so it
  // doesn't keep firing setState on an unmounted component.
  useEffect(() => () => {
    if (progressIntervalRef.current) clearInterval(progressIntervalRef.current);
  }, []);

  const generationStages = useMemo(() => [
    "Analyzing patient demographics and history...",
    "Structuring assessment findings...",
    "Formulating clinical impressions...",
    "Generating plan of care...",
    "Finalizing admission note..."
  ], []);

  const generateAdmissionNote = useCallback(async () => {
    if (!referralData) {
      toast.error("No referral data available");
      return;
    }

    setGenerationStage(0);
    const myReqId = ++generateReqIdRef.current;

    const progressInterval = setInterval(() => {
      setGenerationStage(prev => Math.min(prev + 1, generationStages.length - 1));
    }, 2500);
    progressIntervalRef.current = progressInterval;

    try {
      // Grounded pre-visit draft: the prompt (admissionNotePrompt.js) forbids
      // invented vitals/findings/quotes — undocumented items come back as
      // bracketed blanks the nurse completes during the actual visit.
      const result = await ai.run({
        model: "automatic",
        prompt: buildAdmissionNotePrompt(referralData),
        response_json_schema: ADMISSION_NOTE_SCHEMA
      });

      clearInterval(progressInterval);
      // A newer generation started while this one was in flight — discard this result.
      if (myReqId !== generateReqIdRef.current) return;
      setGenerationStage(generationStages.length - 1);
      setGeneratedNote(result.admission_note || "");
      setEditedNote(result.admission_note || "");

      if (onNoteGenerated) {
        onNoteGenerated({
          note: result.admission_note,
          keyFindings: result.key_findings,
          homeboundStrength: result.homebound_justification_strength,
          carePriorities: result.suggested_care_priorities
        });
      }
    } catch (error) {
      clearInterval(progressInterval);
      console.error('Error generating admission note:', error);
      if (myReqId === generateReqIdRef.current) {
        toast.error('Failed to generate admission note. Please try again.');
      }
    } finally {
      if (myReqId === generateReqIdRef.current) setGenerationStage(0);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps -- AI hook object is intentionally omitted; its run() is stable, and including it would re-fire the call every render
  }, [generationStages, onNoteGenerated, referralData]);

  useEffect(() => {
    if (
      autoGenerate &&
      referralData &&
      !generatedNote &&
      !ai.loading &&
      autoGeneratedForRef.current !== referralData
    ) {
      autoGeneratedForRef.current = referralData;
      generateAdmissionNote();
    }
  }, [autoGenerate, referralData, generateAdmissionNote, generatedNote, ai.loading]);

  const handleCopy = () => {
    navigator.clipboard.writeText(isEditing ? editedNote : generatedNote);
  };

  const handleSaveEdit = () => {
    setGeneratedNote(editedNote);
    setIsEditing(false);
    if (onNoteGenerated) {
      onNoteGenerated({ note: editedNote });
    }
  };

  if (ai.loading) {
    return (
      <Card>
        <CardContent className="p-6">
          <ProgressFeedback
            stages={generationStages}
            currentStage={generationStage}
            message="Generating Admission Note"
          />
        </CardContent>
      </Card>
    );
  }

  if (!generatedNote) {
    return (
      <Card className="border-2 border-navy-300">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-navy-600" />
            AI Admission Note Generator
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-slate-600 mb-4">
            Draft a pre-visit admission note template from the extracted referral data. Only documented
            facts are used — anything the referral doesn't document is left as a bracketed blank to
            complete during the actual admission visit.
          </p>
          <Button 
            onClick={generateAdmissionNote}
            className="bg-navy-600 hover:bg-navy-700"
          >
            <Sparkles className="w-4 h-4 mr-2" />
            Generate Admission Note
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-2 border-navy-300">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-navy-600" />
              Admission Note Draft (pre-visit)
            </CardTitle>
            <AIFieldIndicator
              needsVerification
              tooltip="AI pre-visit draft from the referral only — complete every bracketed blank and verify all values during the admission visit"
            />
          </div>
          <div className="flex gap-2">
            {isEditing ? (
              <>
                <Button size="sm" variant="outline" onClick={() => {
                  setEditedNote(generatedNote);
                  setIsEditing(false);
                }}>
                  Cancel
                </Button>
                <Button size="sm" onClick={handleSaveEdit} >
                  <Save className="w-4 h-4 mr-1" />
                  Save
                </Button>
              </>
            ) : (
              <>
                <Button size="sm" variant="outline" onClick={handleCopy}>
                  <Copy className="w-4 h-4 mr-1" />
                  Copy
                </Button>
                <Button size="sm" variant="outline" onClick={() => setIsEditing(true)}>
                  <Edit3 className="w-4 h-4 mr-1" />
                  Edit
                </Button>
                <Button 
                  size="sm" 
                  variant="outline"
                  onClick={() => setShowReviewer(!showReviewer)}
                  className="text-blue-600"
                >
                  <Eye className="w-4 h-4 mr-1" />
                  {showReviewer ? 'Hide' : 'Review'}
                </Button>
                <Button 
                  size="sm" 
                  variant="outline"
                  onClick={generateAdmissionNote}
                  className="text-navy-600"
                >
                  <Sparkles className="w-4 h-4 mr-1" />
                  Regenerate
                </Button>
              </>
            )}
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {isEditing ? (
          <Textarea
            value={editedNote}
            onChange={(e) => setEditedNote(e.target.value)}
            className="min-h-[600px] font-mono text-sm"
          />
        ) : (
          <div className="bg-navy-50 p-6 rounded-lg border border-navy-200">
            <pre className="whitespace-pre-wrap font-sans text-sm text-slate-900 leading-relaxed">
              {generatedNote}
            </pre>
          </div>
        )}
        
        <div className="mt-4 p-4 bg-blue-50 rounded-lg border border-blue-200">
          <div className="flex items-start gap-2">
            <CheckCircle2 className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-semibold text-blue-900 mb-1">Pre-visit draft — not a record of care</p>
              <p className="text-xs text-blue-800">
                Built only from the referral document; items the referral doesn't document appear as
                bracketed blanks. Complete, correct, and verify everything during the actual admission
                visit before any of this becomes part of the clinical record.
              </p>
            </div>
          </div>
        </div>

        {showReviewer && (
          <div className="mt-4">
            <RealTimeDocumentationReviewer
              noteContent={isEditing ? editedNote : generatedNote}
              noteType="admission"
              patientData={referralData}
              autoAnalyze={true}
              onApplySuggestion={(suggestion) => {
                if (isEditing) {
                  setEditedNote(prev => prev + "\n\n" + suggestion);
                }
              }}
            />
          </div>
        )}
      </CardContent>
    </Card>
  );
}