// FROZEN — pennsync-oasis-response-v1-legacy.
//
// ██ DO NOT EDIT THIS FILE ██
//
// This is a byte-faithful snapshot of the response sets PennSync used BEFORE the
// CMS-aligned cutover, captured from `oasisQuestions.jsx` at commit
// 3348e157290d2ead3b904f96b0bb017f4caa2d67. It exists for exactly one purpose:
// so a response saved under the old meanings can still be DISPLAYED with the
// label it was actually answered under.
//
// Editing it would retroactively change what a stored answer means, which is the
// precise failure this whole cutover exists to prevent. Adding an item here is
// equally wrong: the snapshot is closed. If a legacy label is wrong, it is still
// what the clinician saw, and the record must keep saying so.
//
// Values are recorded as they were stored — JS NUMBERS, because that is what the
// legacy writer persisted. They are deliberately not normalised to strings: a
// legacy `1` and a v2 `"1"` are different facts and the type difference is part
// of the evidence.
//
// NOTHING in v1 is carryable, exportable with a code, or CMS-scorable. That is
// enforced in `registry.js`, not here — this file only remembers.

/** The frozen legacy label for every item whose meaning changed at cutover. */
export const V1_LEGACY_DEFINITIONS = Object.freeze({
  m1033: Object.freeze({
    definition_id: "m1033",
    legacy_item_number: "M1033",
    label: "M1033 — Risk for Hospitalization",
    description: "Which best describes the overall risk for hospitalization for this patient?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Low risk" }),
      Object.freeze({ value: 1, label: "1 — Medium risk" }),
      Object.freeze({ value: 2, label: "2 — High risk" }),
    ]),
  }),
  m1100: Object.freeze({
    definition_id: "m1100",
    legacy_item_number: "M1100",
    label: "M1100 — Patient Living Situation",
    description: "Which of the following best describes the patient's residential circumstance and availability of assistance?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "01 — Patient lives alone with no assistance available" }),
      Object.freeze({ value: 1, label: "02 — Patient lives alone with scheduled assistance" }),
      Object.freeze({ value: 2, label: "03 — Patient lives with others with no assistance from them" }),
      Object.freeze({ value: 3, label: "04 — Patient lives with others who provide assistance" }),
    ]),
  }),
  m1306: Object.freeze({
    definition_id: "m1306",
    legacy_item_number: "M1306",
    label: "M1306 — Unhealed Pressure Ulcer(s)",
    description: "Does the patient have at least one unhealed pressure ulcer/injury at any stage?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — No" }),
      Object.freeze({ value: 1, label: "1 — Yes" }),
    ]),
  }),
  m1340: Object.freeze({
    definition_id: "m1340",
    legacy_item_number: "M1340",
    label: "M1340 — Surgical Wound",
    description: "Does the patient have a surgical wound?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — No" }),
      Object.freeze({ value: 1, label: "1 — Yes — not infected" }),
      Object.freeze({ value: 2, label: "2 — Yes — infected/complications" }),
    ]),
  }),
  m1400: Object.freeze({
    definition_id: "m1400",
    legacy_item_number: "M1400",
    label: "M1400 — Respiratory Status: Dyspnea",
    description: "Shortness of breath or labored breathing observed at assessment.",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Not short of breath" }),
      Object.freeze({ value: 1, label: "1 — Short of breath when walking over 20 feet" }),
      Object.freeze({ value: 2, label: "2 — Short of breath with moderate exertion" }),
      Object.freeze({ value: 3, label: "3 — Short of breath with minimal exertion at rest" }),
      Object.freeze({ value: 4, label: "4 — Short of breath with minimal exertion or at rest" }),
    ]),
  }),
  m1610: Object.freeze({
    definition_id: "m1610",
    legacy_item_number: "M1610",
    label: "M1610 — Urinary Incontinence",
    description: "How often does the patient have urinary incontinence (loss of bladder control)?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — No incontinence or catheter" }),
      Object.freeze({ value: 1, label: "1 — Occasional stress incontinence" }),
      Object.freeze({ value: 2, label: "2 — During day/night; daily pads required" }),
      Object.freeze({ value: 3, label: "3 — All the time; no control" }),
      Object.freeze({ value: 4, label: "NA — Patient has indwelling/suprapubic catheter" }),
    ]),
  }),
  m1620: Object.freeze({
    definition_id: "m1620",
    legacy_item_number: "M1620",
    label: "M1620 — Bowel Incontinence",
    description: "How often does the patient have bowel incontinence (loss of bowel control)?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — No bowel incontinence or ostomy" }),
      Object.freeze({ value: 1, label: "1 — Less than once weekly" }),
      Object.freeze({ value: 2, label: "2 — One to three times per week" }),
      Object.freeze({ value: 3, label: "3 — Four to six times per week" }),
      Object.freeze({ value: 4, label: "4 — Daily or more often" }),
      Object.freeze({ value: 5, label: "5 — Patient has ostomy for bowel elimination" }),
    ]),
  }),
  m1630: Object.freeze({
    definition_id: "m1630",
    legacy_item_number: "M1630",
    label: "M1630 — Ostomy",
    description: "Does the patient have a surgically created ostomy for elimination?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — No ostomy for elimination" }),
      Object.freeze({ value: 1, label: "1 — Patient has ostomy and managing independently" }),
      Object.freeze({ value: 2, label: "2 — Patient has ostomy and requires assistance" }),
    ]),
  }),
  m1740: Object.freeze({
    definition_id: "m1740",
    legacy_item_number: "M1740",
    label: "M1740 — Cognitive, Behavioral & Psychiatric Symptoms",
    description: "Behavioral symptoms that could be due to a cognitive, mental, or behavioral impairment.",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — None of the behaviors" }),
      Object.freeze({ value: 1, label: "1 — Memory deficit / recall difficulty" }),
      Object.freeze({ value: 2, label: "2 — Impaired decision-making" }),
      Object.freeze({ value: 3, label: "3 — Verbal disruption / disruptive behavior" }),
      Object.freeze({ value: 4, label: "4 — Physical aggression" }),
    ]),
  }),
  m1830: Object.freeze({
    definition_id: "m1830",
    legacy_item_number: "M1830",
    label: "M1830 — Bathing",
    description: "Current ability to wash entire body safely. Excludes grooming (washing face, shampooing hair).",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Able to bathe self in shower/tub independently" }),
      Object.freeze({ value: 1, label: "1 — With minimal person assistance to bathe" }),
      Object.freeze({ value: 2, label: "2 — With partial person assistance; patient performs part" }),
      Object.freeze({ value: 3, label: "3 — With extensive person assistance; minimal patient effort" }),
      Object.freeze({ value: 4, label: "4 — Unable to bathe self; total person assistance" }),
      Object.freeze({ value: 5, label: "5 — Unable to bathe self and refused" }),
      Object.freeze({ value: 6, label: "6 — Unable to rate — patient has artificial opening" }),
    ]),
  }),
  m1840: Object.freeze({
    definition_id: "m1840",
    legacy_item_number: "M1840",
    label: "M1840 — Toilet Transferring",
    description: "Current ability to get to and from the toilet or bedside commode safely.",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Able to independently transfer" }),
      Object.freeze({ value: 1, label: "1 — Able to transfer with minimal assistance" }),
      Object.freeze({ value: 2, label: "2 — Able to bear weight and pivot with assistance" }),
      Object.freeze({ value: 3, label: "3 — Unable to bear weight; totally dependent" }),
      Object.freeze({ value: 4, label: "4 — Bedfast, unable to use toilet/commode" }),
    ]),
  }),
  m1860: Object.freeze({
    definition_id: "m1860",
    legacy_item_number: "M1860",
    label: "M1860 — Ambulation/Locomotion",
    description: "Current ability to walk safely, once in a standing position, or use of wheelchair.",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Able to independently walk on all surfaces" }),
      Object.freeze({ value: 1, label: "1 — With minor difficulty on uneven surfaces" }),
      Object.freeze({ value: 2, label: "2 — Requires use of one-handed device" }),
      Object.freeze({ value: 3, label: "3 — Requires use of two-handed device or walker" }),
      Object.freeze({ value: 4, label: "4 — Requires human supervision to ambulate" }),
      Object.freeze({ value: 5, label: "5 — Chairfast, able to wheel self independently" }),
      Object.freeze({ value: 6, label: "6 — Bedfast, unable to ambulate or be up in a chair" }),
    ]),
  }),
  m1870: Object.freeze({
    definition_id: "m1870",
    legacy_item_number: "M1870",
    label: "M1870 — Feeding or Eating",
    description: "Current ability to feed self meals and snacks safely.",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Able to independently feed self" }),
      Object.freeze({ value: 1, label: "1 — Able to feed self with devices or setup help" }),
      Object.freeze({ value: 2, label: "2 — Unable to feed self and needs person assistance" }),
      Object.freeze({ value: 3, label: "3 — Totally dependent on another person" }),
    ]),
  }),
  m2001: Object.freeze({
    definition_id: "m2001",
    legacy_item_number: "M2001",
    label: "M2001 — Drug Regimen Review",
    description: "Was a complete drug regimen review conducted? Did any identified drug issues require follow-up?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — No issues found during review" }),
      Object.freeze({ value: 1, label: "1 — Issues found, physician contacted within 24 hours" }),
      Object.freeze({ value: 2, label: "2 — Issues found, physician not contacted" }),
    ]),
  }),
  m2010: Object.freeze({
    definition_id: "m2010",
    legacy_item_number: "M2010",
    label: "M2010 — High-Risk Drug Education",
    description: "Has the patient/caregiver received education on high-risk drug?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Not applicable — no high-risk drugs" }),
      Object.freeze({ value: 1, label: "1 — Education completed" }),
      Object.freeze({ value: 2, label: "2 — Education not completed" }),
    ]),
  }),
  m2020: Object.freeze({
    definition_id: "m2020",
    legacy_item_number: "M2020",
    label: "M2020 — Management of Oral Medications",
    description: "Patient's current ability to prepare and take all oral medications reliably and safely.",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — Able to independently take correct medications" }),
      Object.freeze({ value: 1, label: "1 — Able if given daily reminders" }),
      Object.freeze({ value: 2, label: "2 — Able to take only if medication is prepared" }),
      Object.freeze({ value: 3, label: "3 — Unable to take medication" }),
    ]),
  }),
  m2401: Object.freeze({
    definition_id: "m2401",
    legacy_item_number: "M2401",
    label: "M2401 — Intervention Synopsis",
    description: "Were intervention(s) implemented to address medication issues?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 0, label: "0 — No" }),
      Object.freeze({ value: 1, label: "1 — Yes" }),
      Object.freeze({ value: 9, label: "NA — No medication issues identified" }),
    ]),
  }),
  m2420: Object.freeze({
    definition_id: "m2420",
    legacy_item_number: "M2420",
    label: "M2420 — Discharge Disposition",
    description: "Where is the patient after discharge from agency?",
    shape: "radio",
    options: Object.freeze([
      Object.freeze({ value: 1, label: "1 — Remained in community (not in facility)" }),
      Object.freeze({ value: 2, label: "2 — Transferred to hospital" }),
      Object.freeze({ value: 3, label: "3 — Transferred to rehab facility" }),
      Object.freeze({ value: 4, label: "4 — Transferred to nursing home" }),
      Object.freeze({ value: 5, label: "5 — Other" }),
      Object.freeze({ value: 9, label: "UK — Unknown" }),
    ]),
  }),
});

/** The 18 ids frozen in v1. Exported so a test can assert the set never drifts. */
export const V1_FROZEN_IDS = Object.freeze(Object.keys(V1_LEGACY_DEFINITIONS).sort());

/**
 * The warning that must accompany every legacy response wherever it is shown.
 * One string, one place — so print, copy, PDF and the item panel cannot drift.
 */
export const V1_LEGACY_WARNING =
  "Legacy PennSync response set—do not copy this code. Answer the official item "
  + "again from the wording in your EMR.";

/** @param {string} definitionId */
export function v1Definition(definitionId) {
  return V1_LEGACY_DEFINITIONS[String(definitionId || "").toLowerCase()] || null;
}

/**
 * The label a legacy value was answered under, or "" when the value is not one
 * the frozen set knows. Display-only: never returns something carryable.
 */
export function v1LabelFor(definitionId, value) {
  const def = v1Definition(definitionId);
  if (!def) return "";
  const hit = def.options.find((o) => o.value === value || String(o.value) === String(value));
  return hit ? hit.label : "";
}
