import { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { 
  History, 
  Loader2, 
  TrendingUp, 
  TrendingDown, 
  Minus,
  AlertTriangle,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  FileText,
  Calendar
} from "lucide-react";

export default function PatientHistorySummary({ 
  patientId, 
  patientName, 
  diagnosis,
  previousVisits = [],
  carePlans = [],
  onInsertSummary 
}) {
  const [summary, setSummary] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isExpanded, setIsExpanded] = useState(true);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Auto-generate summary when patient is selected
  useEffect(() => {
    if (patientId && previousVisits.length > 0 && !autoGenerated) {
      generateSummary();
      setAutoGenerated(true);
    }
  }, [patientId, previousVisits.length]);

  const generateSummary = async () => {
    if (!patientId || previousVisits.length === 0) return;

    setIsLoading(true);
    try {
      // Compile visit data
      const visitData = previousVisits.slice(0, 5).map(v => ({
        date: v.visit_date,
        type: v.visit_type,
        notes: v.nurse_notes?.substring(0, 500) || 'No notes',
        vitals: v.vital_signs
      }));

      const carePlanData = carePlans.filter(cp => cp.status === 'active').map(cp => ({
        problem: cp.problem,
        goal: cp.goal,
        status: cp.status
      }));

      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Summarize this patient's recent clinical history for a nurse about to document a new visit.

PATIENT: ${patientName}
DIAGNOSIS: ${diagnosis || 'Not specified'}

RECENT VISITS (${previousVisits.length} total):
${JSON.stringify(visitData, null, 2)}

ACTIVE CARE PLANS:
${JSON.stringify(carePlanData, null, 2)}

Create a concise clinical summary that includes:
1. Overall clinical status and trajectory (improving/stable/declining)
2. Key trends in vital signs if available
3. Unresolved issues from previous visits
4. Active care plan goals and progress
5. Important things to assess/follow up on today

Also provide a narrative introduction that can be inserted into today's note.

Return JSON:
{
  "overall_status": "improving" | "stable" | "declining" | "mixed",
  "status_rationale": "Brief explanation of status determination",
  "key_trends": [
    {
      "metric": "What is trending",
      "direction": "up" | "down" | "stable",
      "significance": "Clinical significance"
    }
  ],
  "unresolved_issues": [
    {
      "issue": "The issue",
      "last_noted": "When it was last noted",
      "priority": "high" | "medium" | "low"
    }
  ],
  "care_plan_summary": [
    {
      "goal": "The goal",
      "progress": "brief progress note"
    }
  ],
  "focus_areas_today": [
    "What to focus on during this visit"
  ],
  "narrative_intro": "A 2-3 sentence narrative introduction suitable for starting today's note, referencing previous visit findings and what to follow up on",
  "last_visit_summary": "One sentence summary of the most recent visit"
}`,
        response_json_schema: {
          type: "object",
          properties: {
            overall_status: { type: "string" },
            status_rationale: { type: "string" },
            key_trends: { type: "array", items: { type: "object" } },
            unresolved_issues: { type: "array", items: { type: "object" } },
            care_plan_summary: { type: "array", items: { type: "object" } },
            focus_areas_today: { type: "array", items: { type: "string" } },
            narrative_intro: { type: "string" },
            last_visit_summary: { type: "string" }
          }
        }
      });

      setSummary(result);
    } catch (error) {
      console.error("Error generating summary:", error);
    }
    setIsLoading(false);
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'improving': return <TrendingUp className="w-4 h-4 text-green-600" />;
      case 'declining': return <TrendingDown className="w-4 h-4 text-red-600" />;
      case 'stable': return <Minus className="w-4 h-4 text-blue-600" />;
      default: return <AlertTriangle className="w-4 h-4 text-yellow-600" />;
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'improving': return 'bg-green-100 text-green-800 border-green-300';
      case 'declining': return 'bg-red-100 text-red-800 border-red-300';
      case 'stable': return 'bg-blue-100 text-blue-800 border-blue-300';
      default: return 'bg-yellow-100 text-yellow-800 border-yellow-300';
    }
  };

  const getTrendIcon = (direction) => {
    switch (direction) {
      case 'up': return <TrendingUp className="w-3 h-3" />;
      case 'down': return <TrendingDown className="w-3 h-3" />;
      default: return <Minus className="w-3 h-3" />;
    }
  };

  if (!patientId) {
    return (
      <Card className="border-slate-200">
        <CardContent className="p-4 text-center text-slate-500 text-sm">
          <History className="w-8 h-8 mx-auto mb-2 text-slate-300" />
          Select a patient to see history summary
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-blue-200">
      <CardHeader 
        className="py-2 bg-gradient-to-r from-blue-50 to-cyan-50 cursor-pointer"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <CardTitle className="flex items-center justify-between text-sm">
          <div className="flex items-center gap-2">
            <History className="w-4 h-4 text-blue-600" />
            Patient History Summary
            {summary && (
              <Badge className={`${getStatusColor(summary.overall_status)} text-xs`}>
                {getStatusIcon(summary.overall_status)}
                <span className="ml-1">{summary.overall_status}</span>
              </Badge>
            )}
          </div>
          <div className="flex items-center gap-1">
            {isLoading && <Loader2 className="w-3 h-3 animate-spin" />}
            <Button
              variant="ghost"
              size="sm"
              className="h-6 w-6 p-0"
              onClick={(e) => { e.stopPropagation(); generateSummary(); }}
            >
              <RefreshCw className="w-3 h-3" />
            </Button>
            {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </div>
        </CardTitle>
      </CardHeader>

      {isExpanded && (
        <CardContent className="p-3 space-y-3 max-h-96 overflow-y-auto">
          {previousVisits.length === 0 ? (
            <p className="text-xs text-slate-500 text-center py-4">
              No previous visits found for this patient.
            </p>
          ) : !summary ? (
            <div className="text-center py-4">
              <Button size="sm" onClick={generateSummary} disabled={isLoading}>
                {isLoading ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <History className="w-4 h-4 mr-2" />}
                Generate Summary
              </Button>
            </div>
          ) : (
            <>
              {/* Quick Stats */}
              <div className="flex items-center gap-2 text-xs text-slate-600">
                <Calendar className="w-3 h-3" />
                <span>{previousVisits.length} previous visits</span>
                <span>•</span>
                <span>{carePlans.filter(c => c.status === 'active').length} active care plans</span>
              </div>

              {/* Status Rationale */}
              <Alert className={`py-2 ${getStatusColor(summary.overall_status)}`}>
                <AlertDescription className="text-xs">
                  {summary.status_rationale}
                </AlertDescription>
              </Alert>

              {/* Last Visit */}
              {summary.last_visit_summary && (
                <div className="bg-slate-50 p-2 rounded text-xs">
                  <p className="font-semibold text-slate-700 mb-1">Last Visit:</p>
                  <p className="text-slate-600">{summary.last_visit_summary}</p>
                </div>
              )}

              {/* Key Trends */}
              {summary.key_trends?.length > 0 && (
                <div className="space-y-1">
                  <p className="text-xs font-semibold text-slate-600">Trends:</p>
                  <div className="space-y-1">
                    {summary.key_trends.slice(0, 3).map((trend, idx) => (
                      <div key={idx} className="flex items-center gap-2 text-xs bg-white p-1.5 rounded border">
                        {getTrendIcon(trend.direction)}
                        <span className="font-medium">{trend.metric}</span>
                        <span className="text-slate-500">- {trend.significance}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Unresolved Issues */}
              {summary.unresolved_issues?.length > 0 && (
                <div className="space-y-1">
                  <p className="text-xs font-semibold text-slate-600 flex items-center gap-1">
                    <AlertTriangle className="w-3 h-3 text-yellow-500" />
                    Unresolved Issues
                  </p>
                  <div className="space-y-1">
                    {summary.unresolved_issues.map((issue, idx) => (
                      <div key={idx} className="text-xs bg-yellow-50 p-1.5 rounded border border-yellow-200">
                        <div className="flex items-center justify-between">
                          <span>{issue.issue}</span>
                          <Badge className={`text-xs py-0 ${
                            issue.priority === 'high' ? 'bg-red-100 text-red-800' : 
                            issue.priority === 'medium' ? 'bg-yellow-100 text-yellow-800' : 
                            'bg-slate-100 text-slate-800'
                          }`}>{issue.priority}</Badge>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Focus Areas Today */}
              {summary.focus_areas_today?.length > 0 && (
                <div className="space-y-1">
                  <p className="text-xs font-semibold text-slate-600 flex items-center gap-1">
                    <CheckCircle2 className="w-3 h-3 text-green-500" />
                    Focus Today
                  </p>
                  <ul className="text-xs space-y-0.5">
                    {summary.focus_areas_today.slice(0, 4).map((focus, idx) => (
                      <li key={idx} className="flex items-start gap-1 text-slate-700">
                        <span className="text-green-500 mt-0.5">•</span>
                        {focus}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Insert Narrative Button */}
              {summary.narrative_intro && (
                <Button
                  size="sm"
                  variant="outline"
                  className="w-full text-xs gap-2"
                  onClick={() => onInsertSummary(summary.narrative_intro)}
                >
                  <FileText className="w-3 h-3" />
                  Insert History Intro into Note
                </Button>
              )}
            </>
          )}
        </CardContent>
      )}
    </Card>
  );
}