import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileDown, Loader2 } from "lucide-react";
import jsPDF from "jspdf";
import { todayEastern } from "../utils/timezone";

export default function SmartNotePDFExporterEnhanced({ finalNote, patient, visitType, analysisScore, currentUser }) {
  const [exporting, setExporting] = useState(false);

  const exportPDF = async () => {
    if (!finalNote) return;
    setExporting(true);

    try {
      const doc = new jsPDF("p", "mm", "letter");
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - 2 * margin;
      let yPos = margin;

      // Header with patient info
      doc.setFontSize(16);
      doc.setFont(undefined, "bold");
      doc.text("CLINICAL NURSING NOTE", margin, yPos);
      yPos += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, "normal");
      doc.setTextColor(80, 80, 80);

      // Patient identifiers
      const patientInfo = [
        `Patient: ${patient?.first_name || "N/A"} ${patient?.last_name || "N/A"}`,
        `DOB: ${patient?.date_of_birth || "Not on file"}`,
        `MRN: ${patient?.medical_record_number || "Not on file"}`,
      ];

      patientInfo.forEach((info) => {
        doc.text(info, margin, yPos);
        yPos += 5;
      });

      yPos += 2;

      // Visit and document details
      const visitInfo = [
        `Visit Type: ${visitType?.replace(/_/g, " ").toUpperCase() || "N/A"}`,
        `Date: ${todayEastern()}`,
        `Documented by: ${currentUser?.full_name || "N/A"}`,
        `Compliance Score: ${analysisScore || "N/A"}%`,
      ];

      doc.setFont(undefined, "bold");
      doc.setFontSize(9);
      visitInfo.forEach((info) => {
        doc.text(info, margin, yPos);
        yPos += 4;
      });

      yPos += 3;
      doc.setDrawColor(150, 150, 150);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 5;

      // Clinical note content
      doc.setFont(undefined, "normal");
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);

      const lines = doc.splitTextToSize(finalNote, contentWidth);
      lines.forEach((line) => {
        if (yPos > pageHeight - margin - 20) {
          doc.addPage();
          yPos = margin;
        }
        doc.text(line, margin, yPos);
        yPos += 5;
      });

      yPos += 10;
      if (yPos > pageHeight - margin - 20) {
        doc.addPage();
        yPos = margin;
      }

      // Signature line
      doc.setDrawColor(0, 0, 0);
      doc.line(margin, yPos, margin + 50, yPos);
      yPos += 3;
      doc.setFont(undefined, "bold");
      doc.setFontSize(9);
      doc.text("Signature / Provider Print", margin, yPos);

      yPos += 8;
      doc.line(margin + 70, yPos - 5, margin + 120, yPos - 5);
      doc.text("Date", margin + 70, yPos);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by Penn Sync | ${new Date().toLocaleString()}`, margin, pageHeight - 5);

      // Save PDF
      const filename = `${patient?.last_name || "Patient"}_${todayEastern()}_ClinicalNote.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error("PDF export error:", err);
      alert("Failed to export PDF. Please try again.");
    } finally {
      setExporting(false);
    }
  };

  return (
    <Button
      onClick={exportPDF}
      disabled={!finalNote || exporting}
      variant="outline"
      className="h-12 sm:h-10 gap-2 font-semibold"
    >
      {exporting ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Exporting…
        </>
      ) : (
        <>
          <FileDown className="w-4 h-4" />
          Export PDF
        </>
      )}
    </Button>
  );
}